### PR TITLE
Fix TS / runtime errors while using `graphql@15`

### LINKED ISSUE #1481: OperationTypeNode enum not compatible with graphql v15
I´ve updated to the last release  of apollo gateway and federation with graphql v15
 and I get this error:

image
Apollo source code error stack line:
image

Dependencies:
image

I found that graphql v16 package exports enum "OperationTypeNode" but graphql v15 not export it

v15 screenshot:
image
v16 screenshot:
image

### PR DESCRIPTION
**Pull request by clenfest**
It looks like that although OperationTypeNode existed as an exported type in graphql15, it did not exist as an enum, so the way I'm using it is incorrect in peer dependencies.

Fixes #1481

### CODE REVIEW

File: query-planner-js/src/schema-helper/transformSchema.ts [hunk 1]
```diff
@@ -65,7 +65,7 @@ export function transformSchema(
     query: replaceMaybeType(schemaConfig.query),
     mutation: replaceMaybeType(schemaConfig.mutation),
     subscription: replaceMaybeType(schemaConfig.subscription),
-    directives: replaceDirectives(schemaConfig.directives)
+    directives: replaceDirectives(schemaConfig.directives) as GraphQLDirective[],
```
Comment (trevor-scheer) [inline query-planner-js/src/schema-helper/transformSchema.ts:68]: I'm surprised this works across both versions, wasn't this giving us trouble as one of the `Const...` node types?

**Review by trevor-scheer — APPROVED** [review]

File: .circleci/config.yml [hunk 2]
```diff
@@ -80,6 +80,26 @@ jobs:
...
+      - run:
+          command: npm run clean && npm i
+      - run:
+          command: npm run test:ci
+          environment:
+            JEST_JUNIT_OUTPUT_DIR: "reports/junit/"
+      - store_test_results:
+          path: reports/junit
+      - store_artifacts:
+          path: reports/junit
```
Comment (trevor-scheer) [inline .circleci/config.yml:102]: @abernix I'd be curious to hear if you have any opinions on this. We've run into a couple v15 compat issues, this particular version straddle has a few gotchas. Seems like a reasonable way to catch this in CI.

I found the  `npm run clean && npm i` to workaround a problem where it seemed the TS build was out of date (probably was via the caching, which this breaks/works around). Maybe there's a better way that's still cacheable?

File: subgraph-js/package.json [hunk 3]
```diff
@@ -23,7 +23,10 @@
   "publishConfig": {
     "access": "public"
   },
+  "dependencies": {
+    "apollo-server-types": "^0.9.0 || ^3.0.0"
```
Comment (trevor-scheer) [inline subgraph-js/package.json:27]: Is this a stray addition?

File: query-planner-js/src/schema-helper/transformSchema.ts (hunk 1 above)
Comment (clenfest) [reply query-planner-js/src/schema-helper/transformSchema.ts:68]: It's just casting away the readonly property. The issue we had before was that we had a function returning a `ConstValueNode` which wasn't in the same type hierarchy as `ValueNode`

File: subgraph-js/package.json (hunk 3 above)
Comment (trevor-scheer) [reply subgraph-js/package.json]: 32384c0

Comment (clenfest) [reply subgraph-js/package.json]: I had to add it to get it to work, but I'm not sure why.
