### PR TITLE
Cache control support with federation

### LINKED ISSUE #356: Apollo Federation/Gateway doesn't support Cache Control
It doesn't look like `@apollo/federation@0.9.0` and `@apollo/gateway@0.10.0` support `@cacheControl` directives or cache control hints.

Related: https://github.com/apollographql/apollo-server/issues/3181

### Expected
 
Using static or dynamic cacheControl hints will result in cache-control http headers.

### Actual

No headers are sent, and the hints are empty when `cacheControl: true` in `ApolloServer`.

### Code Example:

```js
import { gql } from 'apollo-server'

const typeDefs = gql`
    type Test @key(fields: "id") @cacheControl(maxAge: 60, scope: PRIVATE) {
        id: ID!
     }
`;

export { typeDefs }
```

Error: `UnhandledPromiseRejectionWarning: GraphQLSchemaValidationError: Unknown directive "cacheControl".`

### PR DESCRIPTION
**Pull request by mandiwise**
This PR allows you to use the `@cacheControl` directive with Apollo Federation. To take advantage of it, you need to be using Apollo Server 3.0.2 or newer in your gateway and all your subgraphs.

Specifically, this PR:
- Changes the `Query._entities` resolver in subgraphs to respect `@cacheControl` directives on the individual types that are in the `_Entity` union. If all entity types returned in a given call have `@cacheControl` directives (or use `info.cacheControl` in their `__resolveReference`), then the field's cache control policy comes from the most restrictive of these directives instead of the default of `defaultMaxAge` (eg uncacheable by default). (If any entity type returned in a call does not specify a cache control policy, then it still defaults to `defaultMaxAge`).
- Provide the full incoming GraphQLRequestContext to `GraphQLDataSource.process`. (Also make it possible for the method to tell if it's running a health check or fetching schemas, as has been requested.)
- In `RemoteGraphQLDataSource`, process HTTP `cache-control` response headers from subgraphs and use them to restrict the operation's overall cache policy. As usual with Apollo Server cache policy, if there is no `cache-control` header from a subgraph then assume the whole operation is not cacheable.

(If you want to support cache control with a non-Apollo Server subgraph, just make sure it returns a proper `cache-control` HTTP header.)

Fixes #356.
Fixes https://github.com/apollographql/apollo-server/issues/5449.
Aided by https://github.com/apollographql/apollo-server/pull/5248.

### CODE REVIEW

**Comment by glasser** [comment]
> The replace method is used instead of the restrict because the default maxAge of 0 for the _entites field will never be overwritten by any value >0 set on the member type's definition when restrict is used. This may create unpredictable results if two different entity types were named in the representations field argument, but it may be fine to omit this edge case for now.

This is a bug in the new AS3 cache control logic. My intention is that defaultMaxAge should not be applied if you use dynamic cache control methods. I will try to get this fix into an AS 3.0.01 ASAP. Thanks for discovering it. https://github.com/apollographql/apollo-server/issues/5488

File: federation-js/src/types.ts [hunk 1]
```diff
@@ -13,6 +13,17 @@ import {
   isObjectType,
 } from 'graphql';
 import { PromiseOrValue } from 'graphql/jsutils/PromiseOrValue';
+import { CacheHint, CachePolicy } from 'apollo-server-types';
+
+declare module 'graphql/type/definition' {
```
Comment (glasser) [inline federation-js/src/types.ts:18]: This is probably not required any more once you rebase on https://github.com/apollographql/federation/pull/875 ?

File: federation-js/src/types.ts [hunk 2]
```diff
@@ -87,6 +98,15 @@ export const entitiesField: GraphQLFieldConfig<any, any> = {
         );
       }
 
+      if (info.cacheControl && info.cacheControl.cacheHint.replace) {
```
Comment (glasser) [inline federation-js/src/types.ts:101]: perhaps
```
if (info.cacheControl?.cacheHint?.replace) {
```

File: federation-js/src/types.ts [hunk 3]
```diff
@@ -87,6 +98,15 @@ export const entitiesField: GraphQLFieldConfig<any, any> = {
...
+        const cacheHint: CacheHint | undefined =
+          info.cacheControl.cacheHintFromType(type);
+
+        if (cacheHint) {
+          info.cacheControl.cacheHint.replace(cacheHint);
```
Comment (glasser) [inline federation-js/src/types.ts:106]: This should be restrict, but requires the bug fix mentioned above.

**Review by glasser — CHANGES_REQUESTED** [review]

File: federation-js/src/types.ts (hunk 3 above)
Comment (glasser) [reply federation-js/src/types.ts:106]: Fix released in 3.0.1 so it should be able to be restrict. I think it's fine for us to release this with the caveat that it doesn't work with 3.0.0.

File: federation-js/src/types.ts (hunk 2 above)
Comment (mandiwise) [reply federation-js/src/types.ts]: Fixed

File: federation-js/src/types.ts (hunk 3 above)
Comment (mandiwise) [reply federation-js/src/types.ts]: Updated to use the `restrict` method with 3.0.1

File: federation-js/src/types.ts (hunk 1 above)
Comment (mandiwise) [reply federation-js/src/types.ts:18]: This still seems to be necessary even after a rebase

File: federation-js/src/types.ts [hunk 4]
```diff
@@ -87,6 +98,15 @@ export const entitiesField: GraphQLFieldConfig<any, any> = {
         );
       }
 
+      if (info.cacheControl?.cacheHint?.restrict) {
+        const cacheHint: CacheHint | undefined =
+          info.cacheControl.cacheHintFromType(type);
+
+        if (cacheHint?.maxAge || cacheHint?.scope) {
```
Comment (glasser) [inline federation-js/src/types.ts:105]: I think this could just be `if (cacheHint)`

File: federation-js/src/types.ts (hunk 1 above)
Comment (glasser) [reply federation-js/src/types.ts:18]: My worry is that if you end up loading both this and apollo-server-core in your project, TypeScript will be sad to see the same declaration twice.

I'm thinking of making a chance so that the type under `cacheControl` is exported from apollo-server-types, so you can do something like:

```
  if ((info as any).cacheControl?.cacheHintFromType) {
    const cacheControl: ResolveInfoCacheControl = info.cacheControl;
    const cacheHint = cacheControl.cacheHintFromType(type);
```

**Review by glasser — COMMENTED** [review]
Let me get out another version of AS with the type I'm mentioning here.

Then the other trick is, it would be nice to have tests, but I could write them as part of the half of https://github.com/apollographql/apollo-server/issues/5449 I was going to do...  So maybe I should just augment this PR with that work when I get the time for it.

**Comment by glasser** [comment]
@mandiwise I rebased, upgraded apollo-server-types to the version I just released, and fixed the above. Later I will add my promised half of the project and write some tests.

**Comment by glasser** [comment]
@mandiwise: I squashed your commits together and rewrote the PR description. This PR now implements cache control for federation, end-to-end. It requires Apollo Server 3.0.2 to work properly. It is tested end to end. I have not had a chance to seek out and update docs in this repo or apollo-server yet, and might not get to that this week.

**Comment by vany0114** [comment]
This is great guys @mandiwise @glasser thanks for tackle this, I've been waiting for this. Do you guys already have an ETA to release it?

**Comment by glasser** [comment]
Once we've got docs and code review!

File: gateway-js/src/datasources/types.ts [hunk 5]
```diff
@@ -1,7 +1,33 @@
...
+  /**
+   * The request to send to the subgraph.
+   */
+  request: GraphQLRequestContext<TContext>['request'];
+  /**
+   * The GraphQLRequestContext for the operation received by the gateway, or
+   * one of the strings if this operation is generated by the gateway without an
+   * incoming request.
+   */
+  topLevelRequestContext:
```
Comment (glasser) [inline gateway-js/src/datasources/types.ts:23]: @trevor-scheer Do you like this name?

Do you like this type or should we go with something more like `{kind: 'health check'}|{kind: 'loading schema'}|{kind: 'incoming operation', requestContext: GraphQLRequestContext}`

Comment (glasser) [reply gateway-js/src/datasources/types.ts:23]: OK, I think we definitely want the `kind` sort of thing in case we want more information associated with health checks etc, so I've rebased the PR so it does that. Still curious if you like the topLevelRequestContext name :) I think it's better than incomingRequestContext because not all are based on incoming requests. Of course the fact that it doesn't always have a requestContext on it is a little odd. 🤷

**Comment by mandiwise** [comment]
The caching docs have been updated in this PR: https://github.com/apollographql/apollo-server/pull/5536

**Comment by glasser** [comment]
I could possibly move the `kind` up a level to be a top level option and then have `incomingRequestContext: GraphQLRequestContext` be a top level option that exists when kind is incoming operation. Thoughts @abernix ?

**Review by glasser — APPROVED** [review]
Adding my approval for technical reasons, but this still needs review by somebody else. To be organized by @abernix.

File: gateway-js/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts [hunk 6]
```diff
@@ -15,6 +15,14 @@ beforeEach(() => {
   fetch.mockReset();
 });
 
+// Right now, none of these tests care what's on topLevelRequestContext, so we
```
Comment (trevor-scheer) [inline gateway-js/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts:18]:
```suggestion
// Right now, none of these tests care what's on incomingRequestContext, so we
```

File: gateway-js/src/datasources/types.ts [hunk 7]
```diff
@@ -1,7 +1,48 @@
...
+       * The GraphQLRequestContext for the operation received by the gateway, or
+       * one of the strings if this operation is generated by the gateway without an
+       * incoming request.
+       */
+      incomingRequestContext: GraphQLRequestContext<TContext>;
+      /**
+       * Equivalent to incomingRequestContext.context (provided here for
+       * backwards compatibility): the object created by the Apollo Server
+       * `context` function.
+       */
```
Comment (trevor-scheer) [inline gateway-js/src/datasources/types.ts:31]: Can we add a `@deprecated` annotation on this doc block?
```suggestion
      /**
       * Equivalent to incomingRequestContext.context (provided here for
       * backwards compatibility): the object created by the Apollo Server
       * `context` function.
       *
       * @deprecated Use `incomingRequestContext.context` instead
       */
```

File: gateway-js/src/datasources/types.ts [hunk 8]
```diff
@@ -1,7 +1,48 @@
...
+      context: GraphQLRequestContext<TContext>['context'];
+    }
+  | {
+      kind: 'health check';
```
Comment (trevor-scheer) [inline gateway-js/src/datasources/types.ts:35]: This is maybe just a bit off of convention. Tempting to make this an enum or enum-esque a la graphql's `Kind` https://github.com/graphql/graphql-js/blob/main/src/language/kinds.ts

That being said, it's not like TS struggles at all with these string types - it'll auto-complete and type-check these `kind` properties just fine as-is.

**Review by trevor-scheer — APPROVED** [review]
💵 🎛 🥳

File: gateway-js/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts (hunk 6 above)
Comment (glasser) [reply gateway-js/src/datasources/__tests__/RemoteGraphQLDataSource.test.ts]: Done

File: gateway-js/src/datasources/types.ts (hunk 7 above)
Comment (glasser) [reply gateway-js/src/datasources/types.ts]: Done (with a few more words)

File: gateway-js/src/datasources/types.ts (hunk 8 above)
Comment (glasser) [reply gateway-js/src/datasources/types.ts]: OK, enum it is.

**Comment by glasser** [comment]
Merged!

Let's do a minor version bump release of federation and gateway tomorrow, and then merge https://github.com/apollographql/apollo-server/pull/5536 too (adding version number references to it).

**Comment by vany0114** [comment]
@glasser Guys I'm trying to use the cache control in a federated schema (using the versions mentioned [here](https://www.apollographql.com/docs/apollo-server/performance/caching/#using-with-federation)) using `type-graphql` but it's not working. I used to have a workaround that was merging the schemas and it was working fine, but after I moved to the latest version I obviously removed it (the workaround) but is not working anymore. 

workaround:
```
const finalSchema = mergeSchemas({
    schemaDirectives: {
      cacheControl: CacheControlDirective,
    },
    schemas: [federatedSchema, schema],
  });
```

I'm registering the `cacheContol` directive in the subgraph like this: 
```
  SchemaDirectiveVisitor.visitSchemaDirectives(schema, {
    cacheControl: CacheControlDirective,
  });
```

Also the enum:
``` 
registerEnumType(CacheScope, {
  name: 'CacheControlScope',
  description: 'Scopt of Cache Control',
});
``` 

Any ideas what might I be missing?

**Comment by glasser** [comment]
@vany0114 I'm not really familiar enough with the details of what you're doing to help out. For example, I'm not sure what the `CacheControlDirective` symbol you have above is; I don't know much about `type-graphql`; and I'm not even sure if you're doing this in a subgraph or in your gateway.  Can you provide a full reproduction example (a repo to `git clone` or a codesandbox.io sandbox, with full instructions of what to do to see the issue)?
