### PR TITLE
Fix missing fields due to loss of specific scope (fixes #396)

### LINKED ISSUE #396: gateway: incorrect query plan generated when spreading interface fragment into multiple implementations
Consider the following query, against the federation demo service:
```graphql
fragment Price on Product {
  price
}

query {
  topProducts {
    __typename
    ... on Book {
      ...Price
    }
    ... on Furniture {
      ...Price
    }
  }
}
```

Apollo gateway generates an incorrect query plan: it should simply pass on an equivalent query to the `products` service, but in fact it entirely omits asking for `price` on `Furniture`, and only asks for it on `Book`.

<details> <summary>Test case to reproduce this on master</summary>

```diff
diff --git packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
index 156f7f93..4f210413 100644
--- packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
+++ packages/apollo-gateway/src/__tests__/buildQueryPlan.test.ts
@@ -768,6 +768,46 @@ describe('buildQueryPlan', () => {
         }
       `);
     });
+
+    it(`should not get confused by a fragment spread multiple times`, () => {
+      const query = gql`
+        fragment Price on Product {
+          price
+        }
+
+        query {
+          topProducts {
+            __typename
+            ... on Book {
+              ...Price
+            }
+            ... on Furniture {
+              ...Price
+            }
+          }
+        }
+      `;
+
+      const queryPlan = buildQueryPlan(buildOperationContext(schema, query));
+
+      expect(queryPlan).toMatchInlineSnapshot(`
+                QueryPlan {
+                  Fetch(service: "product") {
+                    {
+                      topProducts {
+                        __typename
+                        ... on Book {
+                          price
+                        }
+                        ... on Furniture {
+                          price
+                        }
+                      }
+                    }
+                  },
+                }
+            `);
+    });
   });
 
   // GraphQLError: Cannot query field "isbn" on type "Book"
```

Test output excerpt:
```
  ● buildQueryPlan › for abstract types › should not get confused by a fragment spread multiple times

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `buildQueryPlan for abstract types should not get confused by a fragment spread multiple times 1`

    - Snapshot
    + Received

    @@ -4,12 +4,9 @@
            topProducts {
              __typename
              ... on Book {
                price
              }
    -         ... on Furniture {
    -           price
    -         }
            }
          }
        },
      }
```

</details>

### PR DESCRIPTION
**Pull request by pcmanus**
This PR fixes #396.

It includes:
- the test originally posted on apollographql/apollo-server#4281 and later migrated to #172. I did took the liberty to slightly amend that commit because 1) it wasn't compiling anymore and 2) it was including the same test twice (so I changed one of the version to use inline fragments instead of name ones to improve coverage).
- the main fix for the loss of scope (see commit message for details).
- the previous fix actually only fix one of the 2 added tests: the one with named fragments (the original one from #396) still fails due to the planner ignore repeated named fragments when it shouldn't. The 3rd commit fixes this (more details in commit message).
- the last commit is a minor optional cleanup (see commit message).

### CODE REVIEW

File: query-planner-js/src/Scope.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+  constructor(
+    public readonly parentType: TParent,
+    possibleTypes: ReadonlyArray<GraphQLObjectType>,
+    public readonly directives?: ReadonlyArray<DirectiveNode>) {
+    // We need to sort the possible types to make our `identityKey()` method work.
+    this.possibleTypes = [...possibleTypes].sort();
+  }
+
+  private valueIdentityKey(value: ValueNode) : string {
```
Comment (glasser) [inline query-planner-js/src/Scope.ts:15]: Just a quick drive-by comment, not reviewing whole PR.

What standard do these functions have to meet? Do we want to ensure that distinct values (and directives) always map to distinct keys? (I think the answer to this question should be in a comment — if it's fine to have clashes then say so.)

In that case I think we need a fair amount more complexity.  eg, the scalars (at least) should include their type so that `1` and `"1"` are different; lists should be able to differentiate between `["a-b", "c"]` and `["a", "b-c"]`, etc.

One possibility would be just to use the graphql-js printer (`print`), perhaps followed by `stripIgnoredCharacters` and/or a hash or something

Comment (pcmanus) [reply query-planner-js/src/Scope.ts]: Good point. Switched to `print`/`stripIgnoredCharacters`.

Comment (pcmanus) [reply query-planner-js/src/Scope.ts]: One may noticed that in the reworked branch I've just pushed, I've actually removed the use of `print`/`stripIgnoredCharacters` and reverted back to a `valueIdentityKey` method.

The reason is that we ideally want the equality to be a bit more semantic. In particular, it makes sense that argument be non meaningful. Meaning that `@foo(a:1, b:2)` be equal to `@foo(b:2, a:1)`. Doing so is easier by generating the string manually and sorting arguments (fields in input objects are also sorted similarly, which is why we don't use `print` for values either).

I did update the method to distinguish between of different types.

The whole business is arguably a bit hacky, but doing that more cleanly (through a proper equality method) is actually quite a bit more code in this case in javascript, and we agree with @martijn that this was probably not worth bothering.

**Comment by pcmanus** [comment]
Pushed a reworked branch that refactor `Scope` slightly more to fix a few additional issues (avoid potential over-fetch and losing directives due to losing type condition).

File: query-planner-js/src/Scope.ts [hunk 2]
```diff
@@ -0,0 +1,271 @@
...
+
+  /**
+   * A string value that uniquely identify the scope.
+   *
+   * The "identity key" of 2 scope objects can be tested for equality to decide if 2 scopes are equal. This exists
+   * so that scopes can be (kind of) used as map keys: javacript maps always only use reference equality for objects
+   * when used as key, so using this string allows to effectively get value equality.
+   *
+   * Note that the main property this method must ensure is that if 2 scopes have the same `identityKey()`, then they
+   * are semantically equilvalent (their treatment by the query planner is undistiguishable). If 2 scopes are
```
Comment (glasser) [inline query-planner-js/src/Scope.ts:238]: I don't follow what the second sentence is saying here.

The first sentence says "same IK implies equivalent".

The second sentence says "equivalent implies different IK".

Is there a typo in one of the sentences?

File: query-planner-js/src/Scope.ts [hunk 3]
```diff
@@ -0,0 +1,271 @@
...
+   */
+  possibleRuntimeTypes() : ReadonlyArray<GraphQLObjectType> {
+    if (!this.cachedRuntimeTypes) {
+      this.cachedRuntimeTypes = this.computePossibleRuntimeTypes();
+    }
+    return this.cachedRuntimeTypes;
+  }
+
+  private static valueIdentityKey(value: ValueNode) : string {
+    // We distinguish different value types though a leading character with a comma (so the int 3 has key "i'3") to
```
Comment (glasser) [inline query-planner-js/src/Scope.ts:179]: This character is generally called a single quote or apostrophe in English; `,` is a comma.

File: query-planner-js/src/Scope.ts [hunk 4]
```diff
@@ -0,0 +1,271 @@
...
+      case 'Variable':
+        return value.name.value;
+      case 'IntValue':
+        return "i'" + value.value;
+      case 'FloatValue':
+        return "f'" + value.value;
+      case 'EnumValue':
+        return "e'" + value.value;
+      case 'StringValue':
+        return "s'" + value.value;
```
Comment (glasser) [inline query-planner-js/src/Scope.ts:191]: If it's important that "same IK implies equivalent" then this encoding combined with the list and object encodings is not strong enough to achieve that goal: there's a conflict between `["x", "y-s'z"]` and `["x-s'y", "z"]`, for example.

I find in TS that the best way to not have to think hard about string escaping is to just use JSON.stringify.  I think you could make this line be

```
return `s'${ JSON.stringify(value.value) }`;
```

so that the encoding of a string ends up being `s'"foo"` (with those double quotes). I think that's sufficient to make things unambiguous (assuming that all the values for enum name, variable name, field name, etc are valid GraphQL identifiers).

Alternatively, if the only thing keeping you away from using the GraphQL printer is field ordering, we do have [a `sortAST` function in our `apollo-graphql` package](https://github.com/apollographql/apollo-tooling/blob/9b8f34ca0aeb7ec1355eb4af6bdbc47802935609/packages/apollo-graphql/src/transforms.ts#L102-L159) which is already a dependency of our gateway which can be used for this sort of normalization.  (Although it perhaps needs to be updated for the more recent version of the graphql spec where directives can be repeatable, as it assumes you can sort directive applications just by directive name.)

**Review by glasser — COMMENTED** [review]
(again merely interested in the key encoding issue, not the larger algorithm)

File: query-planner-js/src/Scope.ts (hunk 4 above)
Comment (pcmanus) [reply query-planner-js/src/Scope.ts]: Good point about strings in list. I've switched to `JSON.stringify` and fixed the comments typos/errors.

File: query-planner-js/src/QueryPlanningContext.ts [hunk 5]
```diff
@@ -0,0 +1,304 @@
...
+   * inside that new condition.
+   *
+   * Note that it is possible the new condition makes the branch unreachable (meaning that no possible
+   * runtime types can implement/be part of the previous type condition (in the scope) and the new one).
+   * In that case this method returns undefined and the branch should be ignored.
+   */
+  private scopeForFragment(
+    currentScope: Scope,
+    fragment: FragmentDefinitionNode | InlineFragmentNode,
+    fragmentDirectives?: ReadonlyArray<DirectiveNode>
```
Comment (martijnwalraven) [inline query-planner-js/src/QueryPlanningContext.ts:253]: I had to check to see why we didn't just take `directives` from `fragment`, but I now understand these are the directives that are applied either on the `InlineFragmentNode` or the `FragmentSpreadNode` (so not the `FragmentNode`). Maybe `appliedDirectives` would be more clear? And/or a comment?

File: query-planner-js/src/Scope.ts [hunk 6]
```diff
@@ -0,0 +1,259 @@
...
+   */
+  isStrictlyRefining(type: GraphQLCompositeType) : boolean {
+    // This scope will refine the provided type, unless that provided type is a subtype of all
+    // the type in the chain.
+    let scope: Scope | undefined = this;
+    while (scope) {
+      if (scope.parentType !== type && isTypeSubTypeOf(this.context.schema, scope.parentType, type)) {
+        return true;
+      }
+      scope = scope.enclosing;
```
Comment (martijnwalraven) [inline query-planner-js/src/Scope.ts:137]: This falls more under the category of "might be interesting to play with", but since the pattern of iterating over a scope chain is pretty common, that might be a nice use for a generator:

```
  *wholeChain(): Generator<Scope> {
    yield this;
    if (this.enclosing) {
      yield *this.enclosing.wholeChain();
    }
  }
```

File: query-planner-js/src/Scope.ts [hunk 7]
```diff
@@ -0,0 +1,259 @@
...
+   * Computes the set of object types that an object within this scope can have at runtime.
+   */
+  possibleRuntimeTypes() : ReadonlyArray<GraphQLObjectType> {
+    if (!this.cachedRuntimeTypes) {
+      this.cachedRuntimeTypes = this.computePossibleRuntimeTypes();
+    }
+    return this.cachedRuntimeTypes;
+  }
+
+  private static valueIdentityKey(value: ValueNode) : string {
```
Comment (martijnwalraven) [inline query-planner-js/src/Scope.ts:164]: Is encoding the type of the value really necessary here? Since these are used as directive arguments, the values should already be validated I think, so we can be sure their types match the definition?

File: query-planner-js/src/FieldSet.ts [hunk 8]
```diff
@@ -7,16 +7,14 @@ import {
...
 import { getResponseName } from './utilities/graphql';
 import { partition, groupBy } from './utilities/array';
+import { Scope } from './Scope';
 
-export interface Field<
-  TParent extends GraphQLCompositeType = GraphQLCompositeType
-> {
-  scope: Scope<TParent>;
+export interface Field {
+  scope: Scope;
```
Comment (martijnwalraven) [inline query-planner-js/src/FieldSet.ts:17]: What is the reason for removing the type argument here? From what I remember, there were places where it was useful to guarantee that the scope of a `Field` was an object type.

**Review by martijnwalraven — CHANGES_REQUESTED** [review]

File: query-planner-js/src/FieldSet.ts [hunk 9]
```diff
@@ -87,7 +56,7 @@ export function printFields(fields?: FieldSet) {
  */
 export function debugPrintFields(fields?: FieldSet) : string {
   if (!fields) return '[]';
-  return '[' + fields.map(debugPrintField).join(', ') + ']'
+  return '[' + fields.map(f => debugPrintField(f)).join(', ') + ']'
```
[the remark this answers is not in the document]
Comment (pcmanus) [reply query-planner-js/src/FieldSet.ts:59]: Then story is that when I was debugging something I added a 2nd optional boolean argument to `debugPrintField` to selectively show the selection set in the representation, but when I did so, the code above stopped type-checking because the argument of `map` can actually take up to 3 arguments, and the 2nd argument is a `number`, not a `boolean`. So I switched back to the code above. I later remove the flag on `debugPrintField` (the printing ended up ugly and not that useful so figured I wouldn't include it) and just didn't revert this.

With that said, this experience led me to wonder if using arrow functions in this case wasn't a better idea in general. For instance, say I had added a 2nd optional argument to `debugPrintField` that was a `number` (but was not meant to be the index that `map` passes as its callback as 2nd argument). The code would still have type-checked, yet it would not have worked as expected, and that would have been surprising/hard to debug because I just added a new optional argument and hadn't used it yet.

Anyway, I'm considering favouring the use of arrow functions in those cases (and only passing functions directly are arguments when the passed functions has at least as many arguments than expected by the function argument). Opinion?

File: query-planner-js/src/Scope.ts [hunk 10]
```diff
@@ -0,0 +1,259 @@
...
+ * }
+ * ```
+ * still assuming that `v` is of type `V` and assuming that X is a subtype of V, the scope for field
+ * `f` will simply be `V <- X` (instead of `V <- X <- V`) as the outermost `... on V` condition adds
+ * nothing (but scope always preserve the most inner type condition as for a field, this is the type
+ * in which the field is defined). Additionally, if type `X` happens to a _super type_ of `V`, the
+ * scope for `f` would simply be `V`.
+ */
+export class Scope {
+  private cachedRuntimeTypes?: ReadonlyArray<GraphQLObjectType>;
```
[the remark this answers is not in the document]
Comment (pcmanus) [reply query-planner-js/src/Scope.ts:52]: I did notice that syntax at one point, but as most code I saw was using `ReadonlyArray`, I stuck to that without asking myself too much question. Good to know the reason existing code may still use `ReadonlyArray` is just that the `readonly` syntax is new. I'll switch to that, I agree it's slightly nicer.

File: query-planner-js/src/Scope.ts [hunk 11]
```diff
@@ -0,0 +1,259 @@
...
+  }
+
+  /**
+   * Creates a new scope given a top-level type.
+   *
+   * @param context - the query planning context in which this scope is created.
+   * @param parentType - the top-level (and only) type of the created scope.
+   * @returns the newly created scope.
+   */
+  static create(context: QueryPlanningContext, parentType: GraphQLCompositeType) {
```
[the remark this answers is not in the document]
Comment (pcmanus) [reply query-planner-js/src/Scope.ts:74]: The reason is to not expose the constructor because I don't want the 2 last arguments to be provided externally from the class, I want to force the use of `refine`.

Note that I reckon that, as always with programming, this could be written some other way. For instance, we could have only the constructor public (and neither `create` nor `refine`) and have the constructor handle the `refine` logic`. But I find this less clean in its usage. I like expressing the construction of scope as the combination of 1) creating a "root" scope, or 2) refining another scope (applying a type condition really).

File: query-planner-js/src/Scope.ts [hunk 12]
```diff
@@ -0,0 +1,259 @@
...
+    }
+    // Scope always preserve the immediate parent type, but if the new type is already the parent one
+    // and we have not directives to preserve, simply return the existing scope.
+    if (!directives && type === this.parentType) {
+      return this;
+    }
+    return new Scope(this.context, type, directives, Scope.pruneRefinedTypes(this, type));
+  }
+
+  private static pruneRefinedTypes(
```
[the remark this answers is not in the document]
Comment (pcmanus) [reply query-planner-js/src/Scope.ts:106]: Clearly, I bring some habits from Java. That said, I do slightly prefer a `private static` in this case just because `pruneRefinedTypes` is very just an helper for `refine` and this allow to put both method physically close by in the file.

That said, if you think `private static` is sufficiently uncommon in typescript that its worth avoiding, I could easily turn this into a proper (private) method (it's static to slightly simplify the handling of `undefined`, but I could handle it at the call sites instead).

File: query-planner-js/src/Scope.ts (hunk 7 above)
Comment (pcmanus) [reply query-planner-js/src/Scope.ts:164]: Probably not. I just felt this added a layer of security against weird cases I might not be thinking of, and this for not much extra effort. Happy to remove it if you feel this distract more than anything else (which might well be true).

File: query-planner-js/src/FieldSet.ts (hunk 8 above)
Comment (pcmanus) [reply query-planner-js/src/FieldSet.ts:17]: There was a single place we where using `Field<GraphQLObjectType>`, and this was for the argument of the `groupForField` method which is an argument to `splitFields`. Except that this was actually wrong: there is a genuine path (namely, [this call](https://github.com/apollographql/federation/blob/40ad8f545a45a82ad6d34b57dd92971ac223f360/query-planner-js/src/buildQueryPlan.ts#L639)) where the field passed is *not* a `GraphQLObjectType` (notice that the field is force-casted to `Field<GraphQLObjectType>` but that we can absolutely reach this point with, say, an interface). The only reason this didn't break at runtime was that within the  `groupForField` method, the only part that truly cared that the field type was an object type was this call to `getOwningService`: https://github.com/apollographql/federation/blob/40ad8f545a45a82ad6d34b57dd92971ac223f360/query-planner-js/src/buildQueryPlan.ts#L454
And the branch calling that method is only taken if the type is indeed an object type. And taking a step back, the fact that the `groupForField` implementation has this condition:https://github.com/apollographql/federation/blob/40ad8f545a45a82ad6d34b57dd92971ac223f360/query-planner-js/src/buildQueryPlan.ts#L445
makes it clear that the method was never expected to only be applied to case were `parentType` was an object type.

Anyway, all this to say that the one use of `Field<GraphQLObjectType>` we have is incorrect and in need of change. So I figured, if no places remains where the type argument gives us anything, is it worth bothering? And having the type argument meant having it on `Scope`, but in `Scope` that type argument only applies to the most immediate `parentType`, not the other ones in the chain, and that felt a bit "unfair" to me.

Btw, I had meant to add a note on that PR about this change since it's something I happened to run into but wasn't certainly obvious. Sorry for forgetting.

File: query-planner-js/src/Scope.ts (hunk 2 above)
Comment (pcmanus) [reply query-planner-js/src/Scope.ts]: There was a typo. Fixed.

File: query-planner-js/src/Scope.ts (hunk 3 above)
Comment (pcmanus) [reply query-planner-js/src/Scope.ts]: Oops. Fixed.

File: query-planner-js/src/FieldSet.ts (hunk 9 above)
[the remark this answers is not in the document]
Comment (martijnwalraven) [reply query-planner-js/src/FieldSet.ts:59]: Ah yes, I understand the reasoning now. The additional arguments to the `map` closure can definitely be confusing. I'm not against following this as a rule, but if we do we should probably consider writing it down somewhere or even enforcing it with a linting rule. Could also be a good discussion piece for a company wide style guide.

File: query-planner-js/src/Scope.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (martijnwalraven) [reply query-planner-js/src/Scope.ts:74]: Agreed that the use of `refine` shows the intention a lot better. My first thought was that it should be possible to write a public overload declaration for the constructor, but unfortunately TypeScript doesn't allow mixing access levels in overloads. So I think a factory method is a fine alternative. Again, this seems like something we may want to write down (including a convention to use `create` as a default factory method).

File: query-planner-js/src/Scope.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (martijnwalraven) [reply query-planner-js/src/Scope.ts:106]: I don't think making it non-static is necessarily better, if there are no dependencies on the instance. I think a top-level function (private to the module) would be more common, but I'm fine with leaving this as `private static` and perhaps following that example in other places if we think it makes sense there as well.

File: query-planner-js/src/Scope.ts (hunk 7 above)
Comment (martijnwalraven) [reply query-planner-js/src/Scope.ts:164]: I'm not a fan of us having to come up with a custom encoding scheme if we can avoid it, because while it can protect against weird cases it could also be a source of bugs and may have to be tested separately. I'll leave the decision to you, because I don't have a strong opinion here. It seems to me the directive definitions should provide enough protection, but I could very well be missing something.

File: query-planner-js/src/FieldSet.ts (hunk 8 above)
Comment (martijnwalraven) [reply query-planner-js/src/FieldSet.ts:17]: That makes sense. I think that forced cast is unsound code that we should remove (and are in the process of through #702), but if it doesn't currently buy us much and we're unsure of the semantics for a type argument on `Scope` I'm fine with removing it. It would be nice to get more type safety back later, but we can tackle that separately.

**Review by martijnwalraven — APPROVED** [review]
