### PR TITLE
fix(subgraph): support `@contact` directive in `printSubgraphSchema`

### LINKED ISSUE #1094: Schema object is omitted when printed
# Relevant Packages
`@apollo/federation` v0.33.3
`@apollo/subgraph` 0.1.2

To support the `@contact` directive, a `schema` element must be defined. When building a schema using `buildSubgraphSchema` and printing it via `printSubgraphSchema` the [schema element is stripped](https://github.com/apollographql/federation/blob/main/subgraph-js/src/printSubgraphSchema.ts#L107) without any directives applied.

# Example Code
```javascript
const { gql } = require("apollo-server");
const { buildSubgraphSchema } = require("@apollo/federation");
const { printSubgraphSchema } = require("@apollo/subgraph");
const typeDefs = gql`
  directive @contact(
    name: String!
    url: String!
    description: String!
  ) on SCHEMA

  extend type Query {
    hello: String
  }

  schema @contact(name: "hi", url: "https://hi.com", description: "hi") {
    query: Query
  }
`;

const schemaString = printSubgraphSchema(buildSubgraphSchema({ typeDefs }));
console.log(schemaString);
```

# Expected Behavior
The expected value of `schemaString`.
```graphql
directive @contact(name: String!, url: String!, description: String!) on SCHEMA

extend type Query {
  _service: _Service!
  hello: String
}

schema @contact(name: "hi", url: "https://hi.com", description: "hi") {
  query: Query
}
```

# Actual Behavior
```graphql
directive @contact(name: String!, url: String!, description: String!) on SCHEMA

extend type Query {
  _service: _Service!
  hello: String
}
```

### PR DESCRIPTION
**Pull request by lennyburdette**
Print `@contact` directive on schema nodes from the `printSubgraphSchema` function

Fixes #1094

### CODE REVIEW

File: subgraph-js/src/directives.ts [hunk 1]
```diff
@@ -88,7 +107,7 @@ export function isFederationDirective(directive: GraphQLDirective): boolean {
   return federationDirectives.some(({ name }) => name === directive.name);
 }
 
-export const otherKnownDirectives = [TagDirective];
+export const otherKnownDirectives = [TagDirective, ContactDirective];
```
Comment (glasser) [inline subgraph-js/src/directives.ts:110]: It looks like this can have the impact of making composition's `printCoreDirectives` print a broken link to https://specs.apollo.dev/contact/v0.1

Comment (trevor-scheer) [reply subgraph-js/src/directives.ts]: Good catch. Made some small adjustments to how the `ContactDirective` is included and how subgraph directive usages are printed.

**Comment by lennyburdette** [comment]
New directive buckets and comments are very clear and helpful!

File: federation-js/src/composition/compose.ts [hunk 2]
```diff
@@ -364,7 +364,7 @@ export function buildSchemaFromDefinitionsAndExtensions({
   // We only want to include the definitions of other known Apollo directives
   // (currently just @tag) if there are usages.
   const otherKnownDirectivesToInclude =
```
Comment (glasser) [inline federation-js/src/composition/compose.ts:366]: Maybe rename this const to match the thing it's filtering from?

**Review by glasser — APPROVED** [review]
Thanks for taking the suggestion I sent you in Slack! I think this is a lot easier to wrap my head around.
