### PR TITLE
fix: Handle defaulted variables correctly during post-processing

### LINKED ISSUE #300: Apollo Federation gateway breaks upon receiving a query with empty variables section
Apollo federation gateway breaks throwing ``` Cannot convert undefined or null to object ``` upon receiving a graphql query which does not have any variables section. (From our perspective this is a very common use case).

Passing variables as empty object {}, works fine, but it should not be mandated on the caller to explicitly pass empty object.

### PR DESCRIPTION
**Pull request by trevor-scheer**
Fixes #300
(more like https://github.com/apollographql/federation/issues/300#issuecomment-1458660420)

Post-processing doesn't currently account for defaulted variable values in an operation at all. This surfaces as a problem when using conditional directives (`@skip`/`@include`) that use variables with defaulted values (and no corresponding variable provided).

We should collect defaulted variable values from the operation and pass them along with the `variables` we provide to `computeResponse` so these are accounted for.

### CODE REVIEW

**Review by dariuszkuc — APPROVED** [review]

File: gateway-js/src/resultShaping.ts [hunk 1]
```diff
@@ -70,7 +70,11 @@ export function computeResponse({
 
   const parameters = {
     schema: operation.schema,
-    variables: variables ?? {},
+    variables: {
+      ...operation.collectDefaultedVariableValues(),
+      // overwrite and defaulted variables if they are provided
```
Comment (pcmanus) [inline gateway-js/src/resultShaping.ts:75]: Nit: I think the "and" should be removed in that sentence?

**Review by pcmanus — APPROVED** [review]
