### PR TITLE
Fix Schema.clone when directive application happens before definition

### LINKED ISSUE #1768: Schema.clone throws when directive applied before definition
### Actual behavior

This code throws an exception because `@bar` is applied before it's defined:

```ts
import { buildSchema } from "@apollo/federation-internals";
buildSchema(`    
  directive @foo(arg: String @bar) on FIELD
  
  directive @bar on ARGUMENT_DEFINITION
  
  type Query {
    foo: String!
  }
`).clone();
```

```ts
/code/apollographql/federation/internals-js/dist/definitions.js:403
                throw this.schema().blueprint.onGraphQLJSValidationError(this.schema(), new graphql_1.GraphQLError(`Unknown directive "@${nameOrDef}".`));
                ^

Uncaught GraphQLError: Unknown directive "@bar".
    at ArgumentDefinition.applyDirective (/code/apollographql/federation/internals-js/src/definitions.ts:530:11)
    at copyAppliedDirective (/code/apollographql/federation/internals-js/src/definitions.ts:3314:20)
    at /code/apollographql/federation/internals-js/src/definitions.ts:3310:43
    at Array.forEach (<anonymous>)
    at copyAppliedDirectives (/code/apollographql/federation/internals-js/src/definitions.ts:3310:28)
    at copyArgumentDefinitionInner (/code/apollographql/federation/internals-js/src/definitions.ts:3358:3)
    at copyDirectiveDefinitionInner (/code/apollographql/federation/internals-js/src/definitions.ts:3366:5)
    at copy (/code/apollographql/federation/internals-js/src/definitions.ts:3217:5)
    at Schema.clone (/code/apollographql/federation/internals-js/src/definitions.ts:1423:5)
    at /code/apollographql/federation/<repl>.ts:2:184 {
  path: undefined,
  locations: undefined,
  extensions: [Object: null prototype] {}
}
```

### Expected behavior

Calling `.clone` on a schema with a directive that's applied before it's defined works. Specifically, `Schema.clone` should copy directive definitions before calling `copyDirectiveDefinitionInner`.

### Version information

```sh
➜ npm ls @apollo/federation-internals
apollo-federation-monorepo@ /Users/weatherman/code/apollographql/federation
├─┬ @apollo/composition@2.0.1 -> ./composition-js
│ └── @apollo/federation-internals@2.0.1 deduped -> ./internals-js
├── @apollo/federation-internals@2.0.1 -> ./internals-js
├─┬ @apollo/gateway@2.0.1 -> ./gateway-js
│ └── @apollo/federation-internals@2.0.1 deduped -> ./internals-js
├─┬ @apollo/query-graphs@2.0.1 -> ./query-graphs-js
│ └── @apollo/federation-internals@2.0.1 deduped -> ./internals-js
├─┬ @apollo/query-planner@2.0.1 -> ./query-planner-js
│ └── @apollo/federation-internals@2.0.1 deduped -> ./internals-js
└─┬ @apollo/subgraph@2.0.1 -> ./subgraph-js
  └── @apollo/federation-internals@2.0.1 deduped -> ./internals-js
```

### PR DESCRIPTION
**Pull request by benweatherman**
Naively copying directives means that we could try to apply a directive before it's been defined. In the following example, `@foo` tries to apply `@bar` before `@bar` has been defined.

```graphql
directive @foo(arg: String @bar) on FIELD_DEFINITION
directive @bar on ARGUMENT_DEFINITION

type Query {
  hi: String! @foo(arg: "hi")
}
```

To fix this, we need to take a similar approach that we do with types: namely, shallow copy directives so they're all defined, then copy the actual definition.

Fixes #1768

### CODE REVIEW

File: internals-js/src/definitions.ts [hunk 1]
```diff
@@ -3215,9 +3215,16 @@ function copy(source: Schema, dest: Schema) {
...
     dest.addType(newNamedType(type.kind, type.name));
   }
+  // Directives can use other directives in their arguments. So, like types, we first shallow copy
+  // directives so future references to any of them can be dereferenced. We'll copy the actual
+  // definition later after all directives are defined.
   for (const directive of directivesToCopy(source, dest)) {
-    copyDirectiveDefinitionInner(directive, dest.addDirectiveDefinition(directive.name));
+    dest.addDirectiveDefinition(directive.name);
   }
+  for (const directive of directivesToCopy(source, dest)) {
```
Comment (benweatherman) [inline internals-js/src/definitions.ts:3224]: **note** I moved this directly after the calls to `addDirectiveDefinition` and specifically before `copySchemaDefinitionInner`. Putting it after caused a bunch of composition test failures.

Comment (pcmanus) [reply internals-js/src/definitions.ts:3224]: Yes, it actually make sense. That's because `copySchemaDefinitionInner` needs the definitions to be "complete" (have their argument) to properly handle it's directive applications, and more precisely to recognise/handle the `@link` directive (reminder: `@link` itself can actually be renamed, so detecting it is not based on its name, but rather on checking that the argument matches the spec).

**Review by pcmanus — APPROVED** [review]

File: internals-js/src/definitions.ts (hunk 1 above)
Comment (benweatherman) [reply internals-js/src/definitions.ts:3224]: That makes sense, I appreciate the clarification
